# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mc0h4tsLbtTy_eFj6G1W407e4--coKui
"""

import pandas as pd
guruh=pd.DataFrame({
    'Ism':['Dilshodbek',"Oybek",'Imomali','Muxammaddiyor','Asrorbek','Sarvarbek','Jurabek','Ilxom','Shukurullo','Bahtiyor'],
'Familiya':['Ikromaliyev',"Turanboyev",'Nuriddinjonov','Tolibjonov','Alimqulov','Shakirjonov','Tursunaliyev','Abduxakimov','Majidov',"Qo'ldoshev"],
    'Manzili':['Angren shahar','Beshariq', 'Quvasoy', "Bog'dod", 'Namangan', "Bog'dod", "Bog'dod", "Vodil", "Namangan", "Qo'qon"],
    'Tel raqam':['+998908291301', '+998908291891', '+998908291301', '+998908291301', '+998908291301', '+998908291301', '+998908291301', '+998908291301', '+998908291301', '+998908291301',],
    })
print(guruh)

guruh.to_excel('guruh.xlsx')